# Configuration pour Crowdin v2
project_id: "MyTimeline"
api_token_env: "CROWDIN_PERSONAL_TOKEN"
base_path: "."
base_url: "https://api.crowdin.com"

pull_request_title: "New Crowdin translations"
pull_request_labels: ["localization"]
pull_request_assignment: false
preserve_hierarchy: true

files:
  - source: "/frontend/public/locales/fr/common.json"
    translation: "/frontend/public/locales/%two_letters_code%/common.json"
    dest: "/frontend/common.json"
    update_option: "update_as_unapproved"
    
  - source: "/backend/src/main/resources/messages_fr.properties"
    translation: "/backend/src/main/resources/messages_%two_letters_code%.properties"
    dest: "/backend/messages.properties"
    type: "properties"
    update_option: "update_as_unapproved"