project_id: YOUR_PROJECT_ID
api_token: YOUR_API_TOKEN
base_path: .
base_url: 'https://api.crowdin.com'
preserve_hierarchy: 1
files:
  - source: /frontend/public/locales/fr/**/*.json
    translation: /frontend/public/locales/%two_letters_code%/%original_file_name%
    type: json
    update_option: update_as_unapproved
    ignore:
      - '**/node_modules/**'
      - '**/.git/**'
      - '**/.next/**'
  - source: /backend/src/main/resources/i18n/messages_fr.properties
    translation: /backend/src/main/resources/i18n/messages_%locale%.properties
    type: properties
    update_option: update_as_unapproved
    ignore:
      - '**/target/**'
      - '**/.git/**'
