project_id: "YOUR_PROJECT_ID"
api_token: "YOUR_API_TOKEN"
base_path: "."
base_url: "https://api.crowdin.com"
preserve_hierarchy: true

files:
  # Frontend translations
  - source: /frontend/public/locales/fr/**/*.json
    translation: /frontend/public/locales/%two_letters_code%/%original_name%
    type: json
    update_option: update_as_unapproved
    update_method: update_without_changes
    export_pattern: /frontend/public/locales/%two_letters_code%/%original_name%
    ignore:
      - "**/node_modules/**"
      - "**/.git/**"
      - "**/.next/**"

  # Backend translations
  - source: /backend/src/main/resources/i18n/messages_fr.properties
    translation: /backend/src/main/resources/i18n/messages_%locale%.properties
    type: properties
    update_option: update_as_unapproved
    update_method: update_without_changes
    export_pattern: /backend/src/main/resources/i18n/messages_%locale%.properties
    ignore:
      - "**/target/**"
      - "**/.git/**"
